### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by MaryBurshtyn** [NasterVill/LightningTunerV2#1]
In general, your code is clear. But to understand them completely I should know busness sphere of your application. 
Also there are some issues :
in src/components/common/animations/Fade/index.js
row 1: should use ' instead of "

in src/components/common/buttons/ScailingButton/index.js
row 1: should use ' instead of "

in src/components/common/buttons/index.js
row 1: should use ' instead of "
row 3: white spaces are required after opening and before closing brackets

in src/components/common/index.js
row 4: white spaces are required after opening and before closing brackets

in src/components/MeasuringScale/MeasuringArc/MeasuringArc.js
rows 4,5,6,7 should be placed in a separate file 'constants'

in src/components/ModalPicker/index.js
row 1: should use ' instead of "
multiple rows: all mentioned styles should be moved to a separate file 'stytles'

in src/containers/Settings/Settings.js
row 6: should use ' instead of "

in src/containers/Tuner/Tuner.js
row 2: remove unused import 'Dimensions'

in src/containers/Tuner/styles.js
row 4: empty object 'containerStyle' shoud be removed

in src/musicdata/tunings.js
row 1, 2: white spaces are required after opening and before closing brackets,
should use ' instead of "

in src/navigation/topBarButtons.js
row 1: should use ' instead of "

in src/screens/SettingsScreen/styles.js
row 1: white spaces are required after opening and before closing brackets

in src/screens/TuningScreen/styles.js
row 1: white spaces are required after opening and before closing brackets,
should use ' instead of "

**Comment by NasterVill** [comment]
Thank you for your review! Point was taken and now all the issues are fixed. Master branch doesn't have them anymore
